//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TShirtOnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Image
    {
        public int ID { get; set; }
        public string Path { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Status { get; set; }
    
        public virtual Product Product { get; set; }

        internal static Image FromStream(MemoryStream memoryStream)
        {
            throw new NotImplementedException();
        }
    }
}
